---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
- name: gateway
  box: debian/stretch64
  interfaces:
  - network_name: private_network
    virtualbox__intnet: "test-networkd-inside"
    auto_config: false
  - network_name: private_network
    virtualbox__intnet: "test-networkd-outside"
    auto_config: false
- name: inside
  box: debian/stretch64
  interfaces:
  - network_name: private_network
    virtualbox__intnet: "test-networkd-inside"
    auto_config: false
- name: outside
  box: debian/stretch64
  interfaces:
  - network_name: private_network
    virtualbox__intnet: "test-networkd-outside"
    auto_config: false
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
