---
ansible_become: yes

networkd:
  ifaces:
    - name: eth0
      network:
        dhcp: ipv4
    - name: eth1
      address: 192.168.0.10/24
      routes:
        - dest: 10.0.0.0/24
          next_hop: 192.168.0.1
