---
ansible_become: yes

networkd:
  ifaces:
    - name: eth0
      network:
        dhcp: ipv4
    - name: eth1
      address:
        - 10.0.0.10/24
        - 10.0.0.20/24
      routes:
        - dest: 192.168.0.0/24
          next_hop: 10.0.0.1
